# try this either as a .py file or in the python shell
import turtle
# the distance we want the pointer to travel each time
turtle.right(20)
turtle.forward(27)
#jersey begin
turtle.fillcolor('#fb8917')
turtle.begin_fill()
turtle.right(25)
turtle.forward(40)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(20)
turtle.left(135)
turtle.forward(75)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(75)

turtle.left(135)
turtle.forward(20)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(40)
turtle.right(25)
turtle.forward(27)
turtle.right(110)
turtle.circle(13,180)
turtle.right(110)
turtle.end_fill()
#jersey end

#right half
turtle.fillcolor('#880c28')
turtle.begin_fill()
turtle.forward(27)
turtle.up()
turtle.right(75)
turtle.forward(32)
turtle.left(5)
turtle.forward(75)
turtle.right(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(102)
turtle.right(90)
turtle.circle(12,90)
turtle.down()
turtle.end_fill()
#right half end

turtle.up()
turtle.right(110)
turtle.forward(27)
turtle.right(25)
turtle.forward(40)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(20)
turtle.left(135)
turtle.forward(75)
turtle.right(90)
turtle.forward(68)
turtle.right(90)
turtle.forward(77)

#left sleeve
turtle.begin_fill()
turtle.left(135)
turtle.forward(20)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(40)
turtle.right(25)
turtle.end_fill()
#left sleeve end

turtle.hideturtle()
turtle.done()